package edu.estg.utils;

public enum RequestType {
    LOCAL_NODE_LOGIN, LOCAL_NODE_REGISTER, ADD_TRAIN_LINE, FEEDBACK_ADD_TRAIN_LINE,
    PASSENGER_LOGIN, PASSENGER_REGISTER,
    BROADCAST_MESSAGE
}
