package edu.estg.utils;

public enum RequestType {
    LOCAL_NODE_LOGIN, LOCAL_NODE_REGISTER, ADD_TRAIN_LINE, FEEDBACK_ADD_TRAIN_LINE, EVENT_MESSAGE,
    PASSENGER_LOGIN, PASSENGER_REGISTER, GET_CURRENT_LOCAL_NODES, ASSOCIATE_TRAIN_LINE, PASSENGER_MESSAGE, PASSENGER_MESSAGE_FEEDBACK,
    MULTICAST_MESSAGE
}
